import fs from 'node:fs';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import path from 'node:path';
import os from 'node:os';
import {spawnSync} from 'node:child_process';
const args=process.argv.slice(2),site=path.resolve(args.includes('--site-dir')?args[args.indexOf('--site-dir')+1]:fileURLToPath(new URL('..',import.meta.url)));
const window={};const ctx=vm.createContext({window});
for(const f of ['camps.js','planner-data.js'])vm.runInContext(fs.readFileSync(path.join(site,'assets',f),'utf8'),ctx);
const D=window.E17_DIRECTORY,P=window.E17_PLANNER;
assert.equal(P.season,'october-2026');assert.equal(P.weeks.length,1);assert.equal(P.weeks[0].mon,'2026-10-26');assert.equal(P.weeks[0].days,5);
assert.equal(new Set(D.providers.map(p=>p.id)).size,D.providers.length);
for(const p of D.providers){const v=P.byId[p.id];assert(v,p.id);assert(p.source.url.startsWith('http'));assert((v.weeks||[]).every(w=>P.weeks.some(x=>x.id===w)));if(v.price){assert(v.priceBasis);assert.equal(p.checkedOn,'2026-09-05');for(const n of Object.values(v.price))assert(Number.isFinite(n)&&n>=0);}if(!v.weeks?.length){assert(!v.price);assert(!p.availability);}}
assert.equal(D.hafSnapshot.length,0);assert.equal(D.providers.filter(p=>P.byId[p.id].weeks?.length).length,6);
console.log('PASS: October dates, six confirmed listings, provenance, unknown prices and HAF integrity');
if(args.includes('--skip-ui'))process.exit(0);
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'kidsorted-october-'));
fs.cpSync(path.join(site,'assets'),path.join(tmp,'assets'),{recursive:true});
let html=fs.readFileSync(path.join(site,'index.html'),'utf8').replace(/<script defer src="https:[^>]+><\/script>/g,'').replace(/<link[^>]+(?:fonts.googleapis|fonts.gstatic)[^>]*>/g,'');
const test=`<script>
window.addEventListener('load',()=>{try{
const check=(x,m)=>{if(!x)throw Error(m)};
localStorage.setItem('e17planner.v1',JSON.stringify({children:[{id:'old',name:'Summer',age:8}],plan:{1:{old:{type:'leave'}}}}));
localStorage.removeItem(STORE_KEY);state.children=[];state.plan={};loadState();check(state.children.length===0,'summer state leaked');
state.children=[{id:'oct',name:'October Test',age:4,color:CHILD_COLORS[0]}];state.plan={1:{oct:{type:'camp',campId:'all-about-dance',days:[1,2,3,4,5]}}};saveState();renderChildren();renderPlanner();applyFilters();
check(document.querySelector('#plannerTable').textContent.includes('October'),'October grid missing');
check(weekCost(providerById('all-about-dance'),1).value===175,'dance week price');
check(weekCost(providerById('barracudas-woodford'),1).value===215,'Barracudas week price');
check(weekCost(providerById('ymca-y-kidz'),1)===null,'unconfirmed price leaked');
const cal=planCalendarText();check(cal.includes('DTSTART;VALUE=DATE:20261026')&&cal.includes('DTEND;VALUE=DATE:20261031'),'calendar dates');
const url=planShareUrl();check(parseSharedPlan(url.slice(url.indexOf('#')))?.children[0].id==='oct','share round trip');
const old='#plan='+base64urlEncode(JSON.stringify({v:1,children:state.children,plan:state.plan}));check(parseSharedPlan(old)===null,'summer share accepted');
state.children=[];state.plan={};loadState();check(state.children[0].id==='oct'&&state.plan[1].oct.campId==='all-about-dance','persistence');
check(JSON.parse(localStorage.getItem('e17planner.v1')).children[0].id==='old','summer data overwritten');
state.confirmedOnly=true;renderChildren();renderPlanner();applyFilters();check(document.querySelectorAll('#providerGrid .camp-card').length===6,'confirmed filter');
const out=document.createElement('pre');out.id='test-result';out.textContent='OCTOBER_UI_PASS';document.body.append(out);
}catch(e){const out=document.createElement('pre');out.id='test-result';out.textContent='OCTOBER_UI_FAIL: '+e.message;document.body.append(out);}});
</script>`;
fs.writeFileSync(path.join(tmp,'index.html'),html.replace('</body>',test+'</body>'));
const chrome=process.env.CHROME_BIN||(process.platform==='darwin'?'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome':'google-chrome');
const result=spawnSync(chrome,['--headless','--no-sandbox','--disable-gpu','--no-first-run','--disable-dev-shm-usage','--allow-file-access-from-files','--user-data-dir='+path.join(tmp,'profile'),'--timeout=15000','--virtual-time-budget=5000','--dump-dom','file://'+path.join(tmp,'index.html')],{encoding:'utf8',timeout:45000,maxBuffer:10*1024*1024});
const output=result.stdout||'';const actual=output.match(/<pre id="test-result">([^<]+)/)?.[1];
assert.equal(actual,'OCTOBER_UI_PASS',actual||result.error?.message||result.stderr.slice(-1000));
console.log('PASS: browser rendering, confirmed filter, pricing, calendar, persistence and cross-season share isolation');
fs.rmSync(tmp,{recursive:true,force:true});
